# Generated by Django 6.1.1 on 2026-09-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
