# Generated by Django 6.1.1 on 2026-09-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='session_id',
            field=models.CharField(db_index=True, default='legacy-session', max_length=255),
            preserve_default=False,
        ),
    ]
